Payloads
dsluijk/rust-ipv8 pull request #23
Opened 2019-05-22 10:02 UTC by jonay2000

Added 3 original py-ipv8 payloads to test against. (headers and hash removed as that's not supported yet).

Optimized some code and made a benchmark for the decoding process.

2019-05-22 12:49 UTC, NULLx76 requested changes

2019-05-22 12:49 UTC, NULLx76 commented on src/networking/payloads/binmemberauthenticationpayload.rs
> +  /// The global time in the system. Uses a lamport clock system.
This comment is out of place

2019-05-22 12:49 UTC, NULLx76 commented on src/networking/serialization/mod.rs
> +//  #[bench]
We probably need to decide which testing framework to use libtest or something like Criterion.

2019-05-22 12:49 UTC, NULLx76 commented on tests/testpyipv8packets.rs
> +      // TODO i am not entirely sure of the extraction of bits is 100% right. though public does seem plausible.
Important to figure this out

2019-05-22 12:52 UTC, NULLx76 commented on src/networking/serialization/mod.rs
> +//  #[bench]
The bench is only available in `nightly` therefore classified as "unstable" and after quickly looking into it stale as well.

2019-05-22 17:55 UTC, dsluijk approved these changes

2019-05-23 12:40 UTC, NULLx76 commented on src/networking/serialization/mod.rs
> +//  #[bench]
We decided to use the extenal benchmarker Criterion.rs

2019-05-24 09:34 UTC, jonay2000 commented on tests/testpyipv8packets.rs
> +      // TODO i am not entirely sure of the extraction of bits is 100% right. though public does seem plausible.
something to keep in mind

2019-05-24 09:34 UTC, NULLx76 approved these changes

2019-05-24 09:35 UTC, merged